server:
  port: 8080

spring:
  application:
    name: sistema-guias-despacho

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:guiasdb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://duoccazure.b2clogin.com/68889877-6ff0-4a80-86ec-dedafca2bae4/v2.0/
          jwk-set-uri: https://duoccazure.b2clogin.com/duoccazure.onmicrosoft.com/B2C_1_cloud_1_native/discovery/v2.0/keys

azure:
  b2c:
    role-claim-name: extension_Role


aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    session-token: ${AWS_SESSION_TOKEN:}
    region: ${AWS_REGION}
    bucket-name: ${AWS_S3_BUCKET}

logging:
  level:
    org.springframework.security: DEBUG
    com.duocuc.sistemaguiasdespacho: DEBUG
